### ISSUE TITLE
Папка dist при dev сборке

### ISSUE THREAD

**Issue by edstarck** [vedees/webpack-template#10]
Привет!
Подскажи, а как сделать чтоб папка dist собиралась при dev сборке?
Это надо чтоб бекендеры тоже могли отслеживать изменения в стилях и скриптах. Когда он себе подключает app.css и app.js и правит в файлах фронта.
Спасибо!

**Comment by vedees** [comment]
Невозможно и не нужно. 
Все css/js файлы можно получить через локал хост. по пути http://localhost:8081/assets/js/app.js и т.д. со стороны бека слежка будет идти за ними.

Там же будут условия для путей: при деве это будет http://localhost:8081, а при билде обычный '/'

Надеюсь помог =)
