### ISSUE TITLE
copy-webpack-plugin error when update to 6.02 version

### ISSUE THREAD

**Issue by Alecto** [vedees/webpack-template#13]
The error occurs after updating the plugin from version 5.1.1 to the latest version 6.0.2:

![image](https://user-images.githubusercontent.com/8464662/84585909-2ff39a80-ae1d-11ea-975e-3469f74f8916.png)
![image](https://user-images.githubusercontent.com/8464662/84585925-59142b00-ae1d-11ea-82d9-999d37834903.png)

**Comment by Alecto** [comment]
It looks like this code:
`    new CopyWebpackPlugin([
      { from: `${PATHS.src}/${PATHS.assets}img`, to: `${PATHS.assets}img` },
      { from: `${PATHS.src}/${PATHS.assets}fonts`, to: `${PATHS.assets}fonts` },
      { from: `${PATHS.src}/static`, to: '' },
    ]),`

needs to be replaced with the following:
`    new CopyWebpackPlugin({
      patterns: [
        { from: `${PATHS.src}/${PATHS.assets}img`, to: `${PATHS.assets}img` },
        { from: `${PATHS.src}/${PATHS.assets}fonts`, to: `${PATHS.assets}fonts` },
        { from: `${PATHS.src}/static`, to: '' },
      ],
    }),`

It worked for me, but you check.

**Comment by vedees** [comment]
Fixed [commit](https://github.com/vedees/webpack-template/commit/f8dd551e7c5190011740ce75370240466abfd2df)
Stable version: [2.0.0](https://github.com/vedees/webpack-template/releases/tag/2.0)
