### ISSUE TITLE
Развёртывание Webpack'а

### ISSUE THREAD

**Issue by alexkobylansky** [vedees/webpack-template#15]
Здравствуйте!
Пытаюсь загрузить эту сборку с гита.
Прописал "git clone https://github.com/vedees/webpack-template webpack-template", затем "cd webpack-template", 
пишу "npm install", а мне выбивает кучу ошибок. Что-то пошло не так?
Вот ссылка на логи: https://1drv.ms/t/s!AlJBObVj2UYspqBsCMfanT9DybmuJA?e=iirmCr

**Comment by vedees** [comment]
```
# Download repository:
git clone https://github.com/vedees/webpack-template webpack-template

# Go to the app:
cd webpack-template

# Install dependencies:
npm install

# Server with hot reload at http://localhost:8081/
npm run dev

# Output will be at dist/ folder
npm run build
```

Если все еще есть проблемы обнови ноду!
