### ISSUE TITLE
npm run build doesn't work

### ISSUE THREAD

**Issue by ridin2** [vedees/webpack-template#21]

**Comment by vedees** [comment]
Fixed and updated template to webpack 5.

- [Realise link](https://github.com/vedees/webpack-template/releases/tag/v5.0.0)
- [Current branch](https://github.com/vedees/webpack-template/tree/webpack5)

**Comment by vedees** [comment]
Fixed and updated template to webpack 5.

- [Realise link](https://github.com/vedees/webpack-template/releases/tag/v5.0.0)
- [Current branch](https://github.com/vedees/webpack-template/tree/webpack5)
