### ISSUE TITLE
run build not work - if i include fonts in fonts.scss

### ISSUE THREAD

**Issue by bodarev** [vedees/webpack-template#24]
step 1 - include fonts like example - http://joxi.ru/zANve3GUj3exZA
step2 - copy fonts to folder - http://joxi.ru/Grq5YaxtGv3Y8r
step 3 - npm run build, and i am error - https://pastebin.com/raw/vQDv6Bby

help please

**Comment by vedees** [comment]
Fixed and updated template to webpack 5.

- [Realise link](https://github.com/vedees/webpack-template/releases/tag/v5.0.0)
- [Current branch](https://github.com/vedees/webpack-template/tree/webpack5)
