### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by Danielinwonderland** [vedees/webpack-template#6]
После разделения конфигов вебпака в 3 видео появилась такая ошибка:
ERROR in ./src/index.js
Module not found: Error: Can't resolve '/css/main.css' in 'D:\Development\Presentation\src'
 @ ./src/index.js 2:0-22

ERROR in ./src/index.js
Module not found: Error: Can't resolve '/scss/main.scss' in 'D:\Development\Presentation\src'
 @ ./src/index.js 3:0-24

очевидно тут про недоступность файлов, поменял содержимое index.js таким образом
`import './css/main.css'
import './scss/main.scss'
window.Vue = require('vue')`

после этого ошибка поменялась на:

ERROR in ./src/scss/main.scss 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import "utils/libs";
| @import "utils/vars";
| @import "utils/mixins";
 @ ./src/index.js 3:0-25

ERROR in ./src/css/main.css 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> .wrapper {
|     display: flex;
| }
 @ ./src/index.js 2:0-23

проблема с лодером, но что именно не так не понятно

**Comment by vedees** [comment]
Попробуй обновиться: 

* Скачать
`git clone https://github.com/vedees/webpack-template webpack-template`
`cd webpack-template`
`npm install`

* Или:
`git pull`

`npm run dev` Server with hot reload at http://localhost:8081/

`npm run build` Output will be at dist/ folder

Если ошибка повторится - обнови ноду https://nodejs.org/en/
